name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker-compose up -d --build
           docker ps
           curl http://localhost:80/[1-10]
           http://localhost:5601/app/management/kibana/indexPatterns
